### ISSUE TITLE
Output formatter - double quotes

### ISSUE THREAD

**Issue by DoggySmooth** [SigmaHQ/pySigma-backend-elasticsearch#15]
Hi,

Would it be possible to add an output formatter to the backend please?

Example - behavior i wish to have
≠===================≠
sigma rule:
EventID: '4625'

Output:
event.id: "4625" instead of event.id: 4625

Example
≠===================≠
sigma rule:
image: 'C:\\Windows Folder\\' 

Output:
winlog.image: "C:\\Windows Folder" instead of winlog.image: C:\\Windows Folder
≠===================≠

I've seen there was a similar issue closed, but it seemed little bit different than our need.

Would it be possible to implement this functionality?
Is there another way to get my desired output?

I would appreciate you response.

Kind regards!

**Comment by andurin** [comment]
Hi,

what's the issue with the quotes? AFAIK it schouldn't matter there.

Regard
Hendrik

02.02.2023 18:08:02 DoggySmooth ***@***.***>:

**Comment by DoggySmooth** [comment]
Hi!

The behavior I get is that the space matches all strings when it's not enclosed in quotes, for text and keyword type of fields.

From my tests, enclosing it in quotes fixes the issues.

To give you some context, I'm using a custom usecase engine which was using 'sigmac' to generate the elastic queries and pushing them to the elkstack. When using sigmac, it outputs the queries with quotes.

I'm currently trying to migrate from sigmac to pysigma for cleaner code + increase in performance.

Kind regards!

**Comment by Asilias** [comment]
Hi everyone,

I would juste like to update this issue because it is also currently giving me a little headache.

I'm trying to query an elk node over the field <content>. This field is mapped as text. When searching for "A book" in this field, I'm only expecting one result.

The backend returns me "content: A\ book" but when executing this query as a query_string, it returns the whole index because "\<space>" is intended to be used on fields name, not on fields search content (e.g https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax)

I'm using pysigma-backend-elasticsearch version 1.0.3 and my elastic node is on version 7.17

So, I think that, more than an enhancement, this could be considered as a real issue.

Still, thank you for all the work. It is amazingly practical and useful.

Best regards,

**Comment by cospirho** [comment]
Presumably we would just need to change the str_quote_pattern, from
  ```python
str_quote_pattern: ClassVar[Pattern] = re.compile(".")
str_quote_pattern_negation: ClassVar[bool] = True
 ```
  to something like:  
```python
str_quote_pattern: ClassVar[Pattern] = re.compile(r"^$|.*\s.*")
str_quote_pattern_negation: ClassVar[bool] = False
```

And then, could provide a backend option to set this to none, to quote everything.

**Comment by thomaspatzke** [comment]
@cospirho's proposal sounds like a good solution to me. What do you think @andurin?

**Comment by andurin** [comment]
I stepped this a litle bit down and was able to define tests which uncovered that issue.

I would like to ask you about the changes https://github.com/SigmaHQ/pySigma-backend-elasticsearch/compare/main...issue-15 before releasing the next version. 

Does the changes make sense to you?

**Comment by Technici4n** [comment]
The original issue _might_ have been caused by the lack of `"default_operator": "AND"` in the Elasticsearch `query_string` parameters.

**Comment by Koen1999** [comment]
> The original issue _might_ have been caused by the lack of `"default_operator": "AND"` in the Elasticsearch `query_string` parameters.

This comment confuses me a bit, it appears to be about the EQL version whereas this issue is about the Lucene version if I am correct.
