### ISSUE TITLE
Detection field containing '.' is not encapsulated with quotes

### ISSUE THREAD

**Issue by Yadasko** [SigmaHQ/pySigma-backend-elasticsearch#6]
Hello,

We have an issue on the generation of requests by the **sigma-cli** script. When we use the sigma detection rule:

```
detection:
    query_key: evt_host
    selection:
        StartModule|endswith: 'kernel32.dll'
        StartFunction|startswith: 'LoadLibrary'
```

The command `sigma convert -t opensearch -f dsl_lucene -p ecs_windows rule.yaml` result is :

```
{"query": 
   {"bool": 
     {"must": [
       {"query_string": 
         {"query": "StartModule:*kernel32.dll AND StartFunction:LoadLibrary*", "analyze_wildcard": true
         }
        }
       ]}
    }
}
```

When the query is used as this:

`StartModule:*kernel32.dll AND StartFunction:LoadLibrary*`

It returns no results. If we modify the query and add quotes around *kernell32.dll, we do get results:

`StartModule: "*kernel32.dll" AND StartFunction:LoadLibrary*`

The `sigma-cli` script does not escape dots and does not add quotes. It seems that the dot is not detected in the query. Is this an intended result, an issue or are we making mistakes in using the script?

**Comment by thomaspatzke** [comment]
This could be a mismatch between the expectation done for the field type in the index and the type in your index. The backend expects a keyword/wildcard-typed field. If this is not the case, tokenization etc. comes into play and things get complicated, especially when values contain token separators like dots.

I check if this could be the case.

**Comment by thomaspatzke** [comment]
Test done, result was as I already expected.

In the first run [I've added a value with a dot](https://github.com/SigmaHQ/pySigma-backend-elasticsearch/blob/ab97e19004b9492334c56d11cf88dfbb72b8febd/tests/test_backend_elasticsearch_connect.py#L22) using the default mapping. The [test](https://github.com/SigmaHQ/pySigma-backend-elasticsearch/blob/ab97e19004b9492334c56d11cf88dfbb72b8febd/tests/test_backend_elasticsearch_connect.py#L219) failed [because the generated query didn't found a matching document](https://github.com/SigmaHQ/pySigma-backend-elasticsearch/actions/runs/3610799305/jobs/6084800071#step:7:86).

In the second run I've [changed the type of the field containing the dotted value to `keyword`](https://github.com/SigmaHQ/pySigma-backend-elasticsearch/blob/2789355f2d3425f8a5a305bab6f7b3ea470df259/tests/test_backend_elasticsearch_connect.py#L17) and here [the test succeeds](https://github.com/SigmaHQ/pySigma-backend-elasticsearch/actions/runs/3610813083/jobs/6084825450#step:7:39).

The fix would be to change the type of the field to `keyword`. The reason for this is that Sigma expects that the whole value is matched. The Elasticsearch default type (I think it's `text`) only matches on tokens, which is problematic for security use cases.

**Comment by Yadasko** [comment]
Thank you very much for looking into this. We will change the type of some fields to keyword as you mentionned but in the long-term I think our index mappings need to be redefined and be more thought-out.

Thank you again.
